name = "sayyesalready"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "valentines-db"
database_id = "6e51c266-e3de-4433-ae9c-0fc2e02f5f43"
